@startuml
package Library{

    class Figure{
        - drones
        - figureCode
        - description
        - version
        - exclusive
        - exclusivePeriod
    }

    class DSLCode{
    }

    class Sequence{
     - sequenceID
     - name
    }
}

class Organization {
    name
    vatNumber
    website
    phoneNumber
    email
}

class Client{
    - vatNumber
    - name
    - address
    - status
    - representatives
}

enum ClientStatus{
    Created
    Regular
    VIP
    Infringement
    Deleted
}

class Representative {
  - email: String
  - name: String
  - position: String
}

class ShowProposal{
}

class Show{
    - showID
    - showCode
}

class Simulation{
}

class User{
    - email
    - name
    - phoneNumber
    - password
    - role
}

class Admin{
}

class  CRMManager{
}

class CRMCollaborator{
}

class ShowDesigner{
}

class DroneTech{
}

class ShowRequest{
    - client
    - place
    - time
    - numOfDrones
    - duration
    - description
    - attachment
    - showRequestStatus
}

enum ShowRequestStatus {
  Submitted
  UnderReview
  Approved
  Rejected
  Scheduled
}

class MaintenanceHistory{
}

class Inventory{
}

class DroneModel{
}

class Drone{
    - droneModel
    - routine
}

class SequenceStep {
 - duration
 - order
}

/' Relationships '/

' System & User '
Admin         "1"  -  "*"  User  : manages >

' Client Management '
CRMManager    "1"  -- "*"  Client : manages >
Client        "*"  -- "1"  ClientStatus : has >
Client        "*"  -- "1"  CRMCollaborator : contacts >
Client        "*"  -- "1"  Representative : has >

' Show Requests '
CRMManager    "1"  -- "*"  ShowDesigner : assigns >
ShowRequest   "1"  --- "1"  ShowRequestStatus : has >
CRMCollaborator "1" --- "1"  ShowRequest : submits >

' Show Proposal '
CRMCollaborator "1" --- "1"  ShowProposal : manages >

' Show Design '
ShowDesigner   "1" --- "*"  Figure : creates >
ShowDesigner   "1" --- "*"  ShowRequest : designs >

' Show Scheduling '
CRMCollaborator "1" --- "*"  Show : schedules >

' Drone Tech Operations '
DroneTech      "1" --- "1...*"  Drone : manages >
DroneTech      "1" --- "*"  Inventory : manages >
DroneTech      "1" --- "*"  DSLCode : generates >
DroneTech      "1" --- "*"  Figure : tests >
DroneTech      "1" --- "*"  Sequence : tests >
DroneTech      "1" --- "*"  Show : tests >
DroneTech      "1" --- "*"  Simulation : generates >

Drone      "1" --- "*"  MaintenanceHistory : has >
Drone      "1" --- "1"  DroneModel : has >


' Figure Relationships '
Figure         "1" --- "1"  DSLCode : has >

' Show Relationships '
Show           "1" -- "*"  Figure : has >
Show           "1" -- "*"  Sequence : has >

Show           "1" --- "*"  Drone : has >

User "1" -- "1..*" CRMManager : is >
User "1" -- "1..*" ShowDesigner : is >
User "1" -- "1..*" CRMCollaborator : is >
User "1" -- "1..*" DroneTech : is >

Organization "1" -- "1..*" User : has >
Organization "1" -- "1..*" Client : has >

ShowProposal       "1"  -- "1"  Client  : for >

Sequence "1" - "1..*" SequenceStep : has >

SequenceStep "1" -- "1" Figure : has >

Simulation "1" --- "1" Show : simulates >



@enduml
